spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhangqingx/config-server
          username: 846455480@qq.com
          password: zhangqing0718


#服务端口号
server:
  port: 9700

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
